FROM wordpress:php8.1
RUN pecl install xdebug \
	&& echo 'xdebug.mode=debug' >> $PHP_INI_DIR/php.ini \
	&& echo 'xdebug.start_with_request=trigger' >> $PHP_INI_DIR/php.ini \
	&& echo 'xdebug.connect_timeout_ms=3600000' >> $PHP_INI_DIR/php.ini \
	&& echo 'xdebug.discover_client_host=1' >> $PHP_INI_DIR/php.ini \
	&& echo 'xdebug.client_host=host.docker.internal' >> $PHP_INI_DIR/php.ini \
	&& echo 'xdebug.client_port=9003' >> $PHP_INI_DIR/php.ini \
	&& echo 'xdebug.idekey=VSCODE' >> $PHP_INI_DIR/php.ini \
	&& echo 'xdebug.var_display_max_data=512' >> $PHP_INI_DIR/php.ini \
	&& echo 'xdebug.var_display_max_children=-1' >> $PHP_INI_DIR/php.ini \
	&& echo 'xdebug.var_display_max_depth=128' >> $PHP_INI_DIR/php.ini \
	&& docker-php-ext-enable xdebug
RUN apt-get update \
	&& apt-get install --assume-yes --quiet --no-install-recommends gnupg2 subversion mariadb-client less jq \
    && apt-get update && apt-get install -y openssh-client \
       libxml2-dev \
    && docker-php-ext-install soap

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /usr/local/bin/wp
