export const PLUGIN_STATUS_DEBUG_TOGGLE = 'PLUGIN_STATUS_DEBUG_TOGGLE';
export const PLUGIN_STATUS_LOGGING_TOGGLE = 'PLUGIN_STATUS_LOGGING_TOGGLE';
export const SERVICE_DATA_REFRESH = 'SERVICE_DATA_REFRESH';

export const WPCOM_CLOUD_STATUS_REFRESH = 'WPCOM_CLOUD_STATUS_REFRESH';
