name: PHP Tests

on: [pull_request, workflow_dispatch]

jobs:
  php_lint:
    name: PHP Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest WCS
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Switch to PHP 8.1
        run: |
          sudo update-alternatives --set php /usr/bin/php8.1
          sudo update-alternatives --set phar /usr/bin/phar8.1
          sudo update-alternatives --set phar.phar /usr/bin/phar.phar8.1
      - name: Lint
        run: find . -type f -name "*.php" -exec php -l {} \;
  find_latest_versions:
    name: Find supported wordpress and woocommerce versions
    runs-on: ubuntu-latest
    outputs:
      wc-versions: ${{ steps.get_wc_versions_for_matrix.outputs.wc-versions }}
      wp-versions: ${{ steps.get_wp_versions_for_matrix.outputs.wp-versions }}
    steps:
      - name: Checkout latest WCS
        uses: actions/checkout@v2
      - name: Get the 3 latest WP minor versions
        id: get_wp_versions_for_matrix
        run: echo "::set-output name=wp-versions::$(git ls-remote --tags --refs https://github.com/WordPress/WordPress.git | sed 's/.*refs\/tags\///' | php ./bin/get-latest-version.php)"
      - name: Get the 3 latest WC minor versions
        id: get_wc_versions_for_matrix
        run: echo "::set-output name=wc-versions::$(git ls-remote --tags --refs https://github.com/woocommerce/woocommerce.git | sed 's/.*refs\/tags\///' | php ./bin/get-latest-version.php)"
  php_build_and_test:
    name: PHP Unit Test (WP, WC)
    needs: find_latest_versions
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_USER: wp_test
          MYSQL_PASSWORD: wp_test
          MYSQL_DATABASE: wordpress_default
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        wp-version: ${{ fromJSON(needs.find_latest_versions.outputs.wp-versions) }}
        wc-version: ${{ fromJSON(needs.find_latest_versions.outputs.wc-versions) }}
    steps:
      - name: Checkout latest WCS
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Switch to PHP 8.1
        run: |
          sudo update-alternatives --set php /usr/bin/php8.1
          sudo update-alternatives --set phar /usr/bin/phar8.1
          sudo update-alternatives --set phar.phar /usr/bin/phar.phar8.1
      - name: Install composer
        run: |
          ./bin/composer-installer.sh
          sudo mv composer.phar /usr/local/bin/composer
          composer install
      - name: Setup WP and WC
        shell: bash -l {0}
        run: tests/bin/install-wc-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wp-version }} ${{ matrix.wc-version }}
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit -c phpunit.xml.dist
